services:
  - type: web
    name: cofoundaiweb
    env: static
    buildCommand: |
      npm install
      npm run build -- --configuration production
    staticPublishPath: dist/co-found-ai/browser
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
    routes:
      - type: rewrite
        source: /*
        destination: /browser/index.html
        force: true
